version: "3.9"  # optional since v1.27.0
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
  api:
    build:
      # The dot represents for current folder
      context: .
      # In this case the docker file at the root folder
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # Because all services in this docker-compose file will be run on the same network
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
    # The api depend on the service postgres
    # It means the api has to wait for the service Postgres already start
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
